version: "3.7"
services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: a6XtypLo
      POSTGRES_USER: puser
      POSTGRES_DB: products
    ports: 
     - '5632:5632'
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: .
    container_name: services
    image: api
    environment: 
      NODE_ENV: production
    ports: 
     - '9090:9090'
    depends_on: 
      - database
